export enum UserActionTypes {
  GET_USER_REQUEST = "GET_USER_REQUEST",
  GET_USER_SUCCESS = "GET_USER_SUCCESS",
  GET_USER_FAILURE = "GET_USER_FAILURE",
  POST_USER_REQUEST = "POST_USER_REQUEST",
  POST_USER_SUCCESS = "POST_USER_SUCCESS",
  POST_USER_FAILURE = "POST_USER_FAILURE",
  SEARCH_USER_REQUEST = "SEARCH_USER_REQUEST",
  SEARCH_USER_SUCCESS = "SEARCH_USER_SUCCESS",
  SEARCH_USER_FAILURE = "SEARCH_USER_FAILURE",
}
